### ISSUE TITLE
Include information about service agreement on property in Technical Info API?

### ISSUE THREAD

**Issue by joeseos** [on-api/on-api#12]
Some network owners doesn't have service agreement on all their property owners, resulting in different lead time on support tickets for end customers. Some document this in their OSS/BSS system (NA, BBE etc.), but I think it could be interesting to look into if this information could be available in any appropriate API service in ONAPI. Maybe Technical Info and/or Tickets?

**Comment by thoho** [comment]
The standard agreement between SP and CO (ie https://www.ssnf.org/nat-i-varldsklass/avtal/tjansteleverantorsavtalet/) stipulates that the access needs to be flaggen in the address list weather the CO has a service contract with the property owner for that access. Not sure though how and if that is implemented. The reasoning during the development of that agreement was that an SP in theory could opt out of selling to those customers.

**Comment by joeseos** [comment]
> The standard agreement between SP and CO (ie https://www.ssnf.org/nat-i-varldsklass/avtal/tjansteleverantorsavtalet/) stipulates that the access needs to be flaggen in the address list weather the CO has a service contract with the property owner for that access. Not sure though how and if that is implemented. The reasoning during the development of that agreement was that an SP in theory could opt out of selling to those customers.

@thoho - Good point. However, I cannot find anything about this in the address specification.

**Comment by thoho** [comment]
I think the address specification was finalized before the TL-agreement came out... Obviously a reason to update the spec.
The TL-agreement also says the address list needs to contain information if there are preconditions that need to be met to be able to activate certain services, eg. an CPE needs to be upgraded for 1Gb internet, which probably also is not currently handled and is very close to the discussion about portCapacity   (#11).

**Comment by joeseos** [comment]
> I think the address specification was finalized before the TL-agreement came out... Obviously a reason to update the spec.
> The TL-agreement also says the address list needs to contain information if there are preconditions that need to be met to be able to activate certain services, eg. an CPE needs to be upgraded for 1Gb internet, which probably also is not currently handled and is very close to the discussion about portCapacity (#11).

Ok, thanks. Then I'll close this issue and will continue in #11.
