### ISSUE TITLE
Accesses / Feasability should include time in services/available

### ISSUE THREAD

**Issue by joeseos** [on-api/on-api#13]
ISO-8601 RFC-3339 in UTC time zone should be included in services/available so that the customer does not need to wait one day for the new TL to place an order. Example:

        "service": "BB-100-100",
        "connection": "2013-10-12",
        "available": "2020-07-21T23:59:12Z",
        "disconnection": ""

**Comment by teemufrosen** [comment]
This one is already specified correctly if I'm not mistaken. The parameter services/available dataformat points to https://github.com/on-api/on-api/blob/master/2.4.0/common/dataformats.md#date

**Comment by joeseos** [comment]
Closing this as this will be added to v.2.5.0.
