### ISSUE TITLE
OrderEvents vs Events

### ISSUE THREAD

**Issue by thebiffman** [on-api/on-api#21]
I am reading the specification again for the first time in a while. I noticed that on the "start page" of version 2.4 (https://github.com/on-api/on-api/tree/master/2.4.0) there is only a link to OrderEvents, not the "generic object events". But when I look at the files I found https://github.com/on-api/on-api/blob/master/2.4.0/spec/events.md file that defines the "generic object events".

Was the generic events removed from the final specification in favor of keeping it as it is in 2.3? Or are they both part of the specification? I am a bit confused and would appreciate a clarification.

**Comment by Connect9600** [comment]
I have a similar question regarding dhcplookup vs option82lookup. The links are either incorrect, both supported or the changelog desciption is not correct. What was decided on this?

**Comment by joeseos** [comment]
@DanielMaintrac or @teemufrosen - do you know the difference between /events and /orderevents?

**Comment by DanielMaintrac** [comment]
The generic events was added for the future possibility to deprecate orderevents. Both is part of the specification. 
The same goes for dhcplookup both should be added to the table of contents and we should probably clarify which should be the preferred version if its available.

**Comment by teemufrosen** [comment]
Correct @edruid , closing
