### ISSUE TITLE
Subscrptions Endpoint fetch single subscription

### ISSUE THREAD

**Issue by wigerhall** [on-api/on-api#24]
The /Subscriptions Endpoint would be enhanced if a single ref could be called.
For instance subscriptionId, spRefernce or spSubscriptionId. 

Example
/Subscriptions/<subscriptionId>
/Subscriptions/spref/< spRefernce >
/Subscriptions/spSubref/< spSubscriptionId >

It would reduce the load on the server and make it easier to fetch a single sub.

**Comment by joeseos** [comment]
I agree. In my opinion, we should use `spRefernce` to get all services on that spRefernce or `spSubscriptionId` to get info on a specific subscription. The same goes when ordering a service, where `spRefernce` and `spSubscriptionId` should be mandatory and `subscriptionId` should be seen as an internal value for the CO that the SP does not need to store in their systems.

**Comment by teemufrosen** [comment]
Agree on original post! Regarding the use of different customer/subscription parameters, I have elaborated my thoughts in #26

**Comment by DanielMaintrac** [comment]
I agree on original post too. The possibility to fetch a more fine grained dataset should be preferable by all parties. That would also solve much of #26 for those that have not stored the subscriptionId from the original order.
It is however possible to get a subset of subscriptions through the accesses API when a single accessId is fetched, which might solve the issue for some.

**Comment by DanielMaintrac** [comment]
After some further thought, what is the actual use case where you need to fetch a single subscription from this API? The same data is available from the access API.

**Comment by DanielMaintrac** [comment]
Agreed that subscriptions should be included in the "fetch all" access API to make it more lightweight.

**Comment by junetaw** [comment]
@DanielMaintrac: You wrote include, did you really intend that? In order to reduce the data in the fetch all access API then it needs to be removed/excluded.

**Comment by DanielMaintrac** [comment]
> @DanielMaintrac: You wrote include, did you really intend that? In order to reduce the data in the fetch all access API then it needs to be removed/excluded.
I meant excluded, thank you for pointing it out, my previous post is edited.

**Comment by jonjacs** [comment]
Coming back to @junetaw 's earlier comment regarding removal of subscriptions from the access endpoint. Perhaps it should be added to the subscriptions endpoint then?

So this would list all the TL's subscriptions on an accessid:

/subscriptions/accessid/<accessid>

**Comment by junetaw** [comment]
@jonjacs Yes. This issue now ties closely with #47 and comment https://github.com/on-api/on-api/issues/47#issuecomment-1326158342

**Comment by junetaw** [comment]
I propose this to be closed as work is already being done in #47 that overlaps this.
