### ISSUE TITLE
accesses services/available

### ISSUE THREAD

**Issue by Connect9600** [on-api/on-api#27]
The available field used to be part of the availability only and not feasibility. Today its a required field at all times (at least what the spec says). Either it should be removed from the first example and marked as "Available with single access", if the spec is incorrect, or at least allow empty string like the services/disconnection if the KO is unable to provide this value.

**Comment by teemufrosen** [comment]
I agree! It has been updated in the 2.5.0 suggestion, see https://github.com/on-api/on-api/blob/v.2.5.0/2.5.0/spec/accesses.md#servicesavailable

**Comment by joeseos** [comment]
Closing and referring to https://github.com/on-api/on-api/blob/v.2.5.0/2.5.0/spec/accesses.md#servicesavailable
