### ISSUE TITLE
Two way order management

### ISSUE THREAD

**Issue by thoho** [on-api/on-api#3]
Be able to send from CO to SP. (Copied from old google sheets list)

**Addon below by Teemu Frösén on October 20th 2020**

The two way order communication will support all existing business models. ON-API 2.4 supports orders created from SP channels, see orders.md. ON-API 2.5 introduces a new endpoint called co_orders.md which enables automation of orders created from CO channels.

### Existing business models for orders
- Order created from SP channels
- Order created from CO channels
  - Technical service preactivated by CO
  - Technical service not preactivated by CO

### Suggested parameters for new endpoint
- Order
  - coOrderId
  - orderDate
  - deliveryDate
- Customer
  - ssn
  - customerFirstname
  - customerLastName
  - customerPhone
  - customerMobilePhone
  - customerEmail
- Access
  - accessId
  - ~~streetName~~
  - ~~streetNumber~~
  - ~~streetLittera~~
  - ~~entrance~~
  - ~~apartmentNumber~~
  - ~~city~~
  - ~~zipcode~~
- Service
  - service
  - commitment
  - noticePeriod
  - campaign
  - isPreactivated

#### Order created from SP channels - service activated by SP
![image](https://user-images.githubusercontent.com/48377287/96591809-f27dad00-12e7-11eb-8af3-8fdb6d584f17.png)
#### Order created from CO channels - service preactivated by CO
![image](https://user-images.githubusercontent.com/48377287/96591913-15a85c80-12e8-11eb-8715-3437acfd40ba.png)
#### Order created from CO channels - service not preactivated by CO
![image](https://user-images.githubusercontent.com/48377287/96591943-21941e80-12e8-11eb-99ad-1f111666148e.png)

**Comment by joesoes** [comment]
I would prefer that the order inquiry is sent to TL before the customer is given an IP address in the case where the TL does not use opt82 to manage DHCP, as the TL's IP address should be assigned a customer when the order inquiry is completed in the TL's system(s).

![image](https://user-images.githubusercontent.com/906435/83942941-70895d80-a7f8-11ea-998f-840452e222f2.png)

**Comment by joeseos** [comment]
I would prefer that the order inquiry is sent to TL before the customer is given an IP address in the case where the TL does not use opt82 to manage DHCP, as the TL's IP address should be assigned a customer when the order inquiry is completed in the TL's system(s).

![image](https://user-images.githubusercontent.com/906435/83942941-70895d80-a7f8-11ea-998f-840452e222f2.png)

**Comment by teemufrosen** [comment]
Edited original post by @thoho with a proposal to the new two way order functionality. It's a draft, please add your feedback. My own take on the proposed process is that we should in a later version of ON-API enable possibility for SP to acknowledge orders from CO, but for now, agreed data retention rules of orders between each party should be applied on CO Orders.

**Comment by thoho** [comment]
I suggest we remove the address fields (streetName, streetNumber, streetLittera, entrance, apartmentNumber, city, zipcode) from the order information. All this info must be (authoritatively) available through the accesses endpoint. Having the same (or similar) info on multiple endpoints only opens up for inconsistencies.

**Comment by thoho** [comment]
Is it better to name orderId as CoOrderId? Typically a reference both sides will have it's own...

**Comment by teemufrosen** [comment]
Agree on above comments, updated first post in issue.

**Comment by JonasEklundh** [comment]
My comment about the service part is as follows, as the viewpoint of Tjänstekanonen / Tjänsteguiden:

1. Problem is how to communicate exactly what technical service the order pertains to. In some networks we have the service_uid to fallback on, which may or may not be identifiable for the SP. The other is the name of the service as given by the SP (I.e. "Internet 100/100 Mbps"). So the "service" field could be split into two; spService - "Internet 100/100 mbps" and service - "B2-100-100"

2. Many services have "standard" campaigns, and thus no campaign code. I.e. the service may be standard 199 kr/mån and commitment time of 12 months, and the "campaign" shows it as 189 kr/mån at 6 months commitment time, which for the SP is the standard price for the service. Thus, if we include commitmentTime and noticePeriod - should they show the values for the standard service or for the selected campaign. And if it does, shouldn't there also be fields for startFee and monthlyCost, to show the values that are active for the selected campaign.

3. If we forgoe the extra fields above, should the "campaign" field always be a campaign code that the SP needs to keep track of, or could it be used to send along a summary of the selected campiagn? I.e. should it always be "ABC123" or could it be "3 months free, no commitment time", which makes it harder to data-parse of course.

Some examples of what I would prefer:
  service: B2-100-100
  sPservice: Internet 100/100 Mbps
  commitment: 12
  noticePeriod: 6
  startFee: 499
  monthlyCost: 129
  campaign: 
  isPreactivated: false

Now, Bredband2 adds a campaign to the above service, which the end user selects:
  service: B2-100-100
  sPservice: Internet 100/100 Mbps
  commitment: 24
  noticePeriod: 12
  startFee: 0
  monthlyCost: 229
  campaign: PLSTN5
  isPreactivated: false

Note that the end user can still order the first version, without the campaign.

**Comment by teemufrosen** [comment]
"Two way order management" has been implemented in 2.5.0, see new endpoints in 2.5.0. Closing. 

* [coorder.md](https://github.com/on-api/on-api/blob/master/2.5.0/spec_sp/coorder.md)
* [order.md](https://github.com/on-api/on-api/blob/master/2.5.0/spec_sp/order.md)
* [ordernotice.md](https://github.com/on-api/on-api/blob/master/2.5.0/spec_sp/ordernotice.md)
