### ISSUE TITLE
Response issue for /accesses

### ISSUE THREAD

**Issue by domadev812** [on-api/on-api#31]
Hi, Dev team,

If I call https://ispportal.seom.se/api/onapi/2.4/accesses on the Post man, I get the response with json data correctly.

By the way if I call the api in my backend(Node.js), in many cases I get the string instead of json.
I can get json data only 1 or 2 times if I call the api 100 times.

Here is my code.
```
const response = await axios({
    method: 'GET',
    responseType: 'json',
    headers: {
      'content-type': 'application/json'
    },
    auth: {
      username: process.env.OPEN_NETWORK_USER_ID,
      password: process.env.OPEN_NETWORK_USER_PASSWORD,
    },
    url,
    maxContentLength: 1000000000,
    maxBodyLength: 1000000000,
  });
```

I'd like you to check and let me know if I need to add more additional info in axios request.

Here is the screenshot what I can get.
![Screen Shot 2021-03-10 at 11 48 20](https://user-images.githubusercontent.com/29895368/110633407-03e92800-81a9-11eb-8968-d9c97bf4fddb.png)

**Comment by joeseos** [comment]
@domadev812 I suggest that you reach out to SEOM to troubleshoot.

**Comment by domadev812** [comment]
@joeseos 
Thanks for your reply.

I am sorry, but how can I reach out to them?
