### ISSUE TITLE
Suggestion for improved meter's address examples

### ISSUE THREAD

**Issue by mchristenssonTN** [on-api/on-api#37]
In the Accesses API there is an example that I think is missing the last digit:
`In the example of "Lantvägen 550-70", the street number is "550-7".`

I assume that the last 0 is missing? In that case, I also suggest to add this example under streetLittera:
`In the example of "Lantvägen 550-70", the street littera is empty.`

Complete example texts:
`streetNumber`
`In the example of "Kungsgatan 10G", the street number is "10". In the example of "Lantvägen 550-70", the street number is "550-70".`

`streetLittera`
`Street littera or entrance. In the example of "Kungsgatan 10G", the street littera is "G". In the example of "Lantvägen 550-70", the street littera is empty.`

**Comment by joeseos** [comment]
Good point. Please create a pull request and relate to this issue.

**Comment by joeseos** [comment]
Closing as pull request was merged to master.
