### ISSUE TITLE
Support for using spTicketReference instead of spReference in SP Contacts

### ISSUE THREAD

**Issue by joeseos** [on-api/on-api#54]
In my opinion, it should be possible to use spTicketReference instead of spReference in SP Contacts to limit the transaction of personal data, limited to if there is an active SP trouble ticket that is previously shared though tickets API or other manual process. The benefit of this is limiting the transaction of personal data to the scenario where to CO needs to send a technician to the end customer.

**Comment by thoho** [comment]
That would basically create a rather limiting requirement on peoples fault ticket implementations. Eg, it is currently not a requirement to implement both the Contacts and the Tickets API.
A compromise could be that the first call could ask for contact info based on spTicketReference but the responder can answer "spRererence needed" and then the request have to be done again with an spRererence. That would probably accommodate more implementations than just requiring a spTicketReference.
