### ISSUE TITLE
Implementation status ON-API (all versions)

### ISSUE THREAD

**Issue by teemufrosen** [on-api/on-api#6]
This issue is used to report the implementation status of each endpoint for all versions of ON-API. Please apply implementation status for the company or companies that you represent, according to template below. 

Accepted values are: Yes/No/ETA (eg. Q3 2020)

### Version 2.3.1
**Company:
[Availability:](https://github.com/on-api/on-api-release-2.3.1/blob/master/availability.md)
[Feasibility:](https://github.com/on-api/on-api-release-2.3.1/blob/master/feasibility.md)
[Service Activation:](https://github.com/on-api/on-api-release-2.3.1/blob/master/service_activation.md)
[Link status:](https://github.com/on-api/on-api-release-2.3.1/blob/master/fm_linkstatus.md)
[Access customer info:](https://github.com/on-api/on-api-release-2.3.1/blob/master/access_customer_info.md)
[CO Active services:](https://github.com/on-api/on-api-release-2.3.1/blob/master/co_active_services.md)**

### Version 2.4.0
**Company: 
[Accesses:](https://github.com/on-api/on-api/blob/master/2.4.0/spec/accesses.md) 
[Orders:](https://github.com/on-api/on-api/blob/master/2.4.0/spec/orders.md)
[Tickets:](https://github.com/on-api/on-api/blob/master/2.4.0/spec/tickets.md)
[Technical information:](https://github.com/on-api/on-api/blob/master/2.4.0/spec/technical_info.md)
[Contacts:](https://github.com/on-api/on-api/blob/master/2.4.0/spec/contacts.md)
[Subscriptions:](https://github.com/on-api/on-api/blob/master/2.4.0/spec/subscriptions.md)
[Invoice Specification:](https://github.com/on-api/on-api/blob/master/2.4.0/spec/invoice_specification.md)**

As an alternative to commenting in this issue, parties are allowed to commit implementation status of the company or companies that you represent directly to [README on the main repo.](https://github.com/on-api/on-api/blob/master/README.md)

**Comment by jstenmark** [comment]
@joeseos Updated status for Telenor

**Comment by junetaw** [comment]
Set status to No for Junet on all please. 

Question: As the ON-API is primarily from the perspective of the CO; currently I guess the only endpoint of the ON-API that the SP can implement is the Contact information? So the SP listing should only list that for SPs? 

However, if the listing for SPs is to list IF the SP can READ/USE the endpoint, then you can set Junet to YES on all for both versions.

**Comment by gustaf722** [comment]
Version 2.3.1
Company: Viasat
Availability: No
Feasibility: No
Service Activation: No
Link status: No
Access customer info: No
CO Active services:

Version 2.4.0
Company: Viasat
Accesses: No
Orders: No
Tickets: No
Technical information: No
Contacts: No
Subscriptions: No
Invoice Specification: No

This is the current status but we want to move towards ON-API and Flow looks like a good place to start. We can't use developers time if the other end is not ready.

**Comment by thoho** [comment]
> Set status to No for Junet on all please.
> 
> Question: As the ON-API is primarily from the perspective of the CO; currently I guess the only endpoint of the ON-API that the SP can implement is the Contact information? So the SP listing should only list that for SPs?
> 
> However, if the listing for SPs is to list IF the SP can READ/USE the endpoint, then you can set Junet to YES on all for both versions.

We interpreted the questions as if one have implemented "their" side regardless if you're an SP or CO, ie the implementation is either the producer or consumer side depending on your role (and reversed in case of the contats api). Both sides should implement the endpoints api.

**Comment by teemufrosen** [comment]
A new suggestion on how to keep track on implementation status will be presented on next workshop with working group.

**Comment by teemufrosen** [comment]
Until the new suggestion mentioned above is in place, all companies are expected to make a direct commit or create a pull request to update implementation status. Closing.
