### ISSUE TITLE
Order: Add CustomerData to order

### ISSUE THREAD

**Issue by junetaw** [on-api/on-api#69]
Suggested Labels: endpoint/order

Background:
CO's that still send own invoices and therefore wants customer data from the SP are currently limited to and stuck with PI-api 2.2.0 (or maybe a modified 2.3.0). 

Suggested solution:
Allow customer data to be sent with an activation. The data should be optional in the request as not to break any implementation that do not use customer data. It is up to the CO to respond with a failure if the required data is missing.

Example of structure adapted from https://github.com/ComHem/oss-provider-interface-api/blob/master/docs/provider_api_2.2/service_activation.md#orderl%C3%A4ggning-exempel-aktivering:
""customer"": {
        ""firstName"": ""Kalle"",
        ""lastName"": ""Anka"",
        ""socialSecurityNumber"": ""192012317777"",
        ""email"": ""karl@ankeborg.se"",
        ""phone"": ""031-119119"",
        ""mobilePhone"": """",
        ""street"": ""Testvägen 100"",
        ""zipCode"": ""10000"",
        ""city"": ""Ankeborg""
   }"

**Comment by plundgren** [comment]
For GDPR reasons we think that this one should be rejected and that the contact information api should be used instead.

**Comment by junetaw** [comment]
@plundgren and @MaxHellqvist: Please explain further why GDPR would be an issue here? I might have missed something.

The Sending (SP) and Receiving (CO) parties have a binding agreement enabling the transfer of customer data. Getting the customer data directly in the order or requesting it via the contact information api should therefore be equal from that standpoint. 

I think sending it with the order is the only way in both short and long term as most SPs won't be activating their side. The bigger SPs might, the smaller probably not. So the CO will then have to create a separate, time consuming way to get the required data.

By sending it with the order both sides needs minimal implementation and the order is complete straight away.

**Comment by junetaw** [comment]
I have always been a little bit against the SP ON-api side. It adds complexity that will be difficult to handle going forward. My opinion is that tickets/events relating to a specific CO should all always reside IN THAT CO. 

In this case, the CO might create a "Contact information request" and it is published at the CO side endpoint /tickets (or whatever would be a good name). The SP queries (or gRPC) this at intervals and picks up the request, handles it, and responds to it.

No integration is needed FROM the CO TO the SP's system. No maintening urls, versions, logins, and other things.

If the SPs polling interval is suitably quick (probably gRPC is needed) then the same system could be used to SP-validate self activations, get SP-prices for access etc making the SP ON-api obselete.

As COs have a long lead time, having a separate SP ON-api will create a lot of problems. The SP will probably have to support all versions (as long as one CO uses an ON-api version then SP needs to have it as well), smaller SPs will probalbe not have or struggle to implement etc.

**Comment by plundgren** [comment]
@junetaw We feel that it would be safer GDPR-wise if the one who wants the information request it, instead of automatically send it with the order. 

We have seen several orders where customer information has been sent to us by bad routines or by mistake. That we believe could be considered as a GDPR breach. By using the contact information api such mistakes and bad routines is avoided.

**Comment by junetaw** [comment]
@plundgren There are many ways that would be better yes. However there is also a practical side to this. If the SP contact information api is to be used, then nothing will happen probably. I do not know how many SPs that have implemented that, anyone who knows? 

If many SPs haven't implemented it, then the COs that needs customer data will be left on Pi-api 2.2 or ON-api 2.3.0 indefinitely. And we urgently need them upgraded. Leaving them hanging is way worse in my opinion.

A note was added to the commit:
* Note: CO that DO NOT require customer data should throw an exception if incoming data if sent.

That was meant to say that CO, that do not want customer data, should not process the request at all and hopefully it would not count as a breach. 

This was meant as a short term fix to allow COs to upgrade to 2.6 and then we start to "fix" the rest in future versions. My plan was then to, in 2.7, to suggest a move of the contact information api to the CO side instead and significantly bolster potential SP implementation.

I could however try to create a 2.6 PR to move it if necessary, would that satisfy everyone?

**Comment by teemufrosen** [comment]
Needs further discussion, will not be done in current state. New issue will be created.
