### ISSUE TITLE
Broken link to lantmäteriet in accesses spec

### ISSUE THREAD

**Issue by edruid** [on-api/on-api#70]
In https://github.com/on-api/on-api/blob/master/2.5.0/spec/accesses.md this link is broken (returns 404):
> See [lantmateriets guide (swedish)](https://www.lantmateriet.se/contentassets/45acf232634c44c1a47c5ebcb7598e07/handbok_adress.pdf) for more information on meter's address

**Comment by junetaw** [comment]
Affects 2.4 and 2.6 also. I propose to just edit 2.4 and 2.5 and do a PR for 2.6. Or should it be three separate PR?

**Comment by DanielMaintrac** [comment]
@junetaw I agree, remove the link. There is is actually two links on that same page that are broken and both should be removed.

**Comment by teemufrosen** [comment]
Working group meeting: Will update links on master and merge to 2.6.0 branch.
