### ISSUE TITLE
dhcpIdentifier is missing lookup endpoint

### ISSUE THREAD

**Issue by jonjacs** [on-api/on-api#75]
Since option82 was replaced by dhcpIdentifier, shouldn't it also have a lookup endpoint similar to option82? Something for 2.6? 

/onapi/2.6/dhcpIdentifier/

**Comment by junetaw** [comment]
Yes, I seems the change did only affect certain parts and not all. 
Both are mentioned in https://github.com/on-api/on-api/blob/master/2.5.0/common/dataformats.md#option82 where the Option 82 part should be removed for 2.6 and everything that mentions Option 82 should be found and reworked to only use dhcpIdentifier,

**Comment by Xake** [comment]
Are you talking about https://github.com/on-api/on-api/blob/master/2.4.0/spec/dhcplookup.md that was never moved to 2.5.0?

**Comment by teemufrosen** [comment]
Working group meeting: The dhcplookup endpoint was supposed to be moved to 2.5.0 branch, but wasn't due to mistake. Will be reinstated in 2.6.0.
