### ISSUE TITLE
Invoice specification

### ISSUE THREAD

**Issue by teemufrosen** [on-api/on-api#8]
Please leave your feedback for the invoice specification in this issue. 

Describe clearly which columns you wish to leave feedback on. If you want to add new columns, describe the column that you want to add, and what purpose it will serve. 

Link to invoice specification: https://github.com/on-api/on-api/files/4488960/faktura-specifikation-2018-02.xlsx

**Comment by joeseos** [comment]
Not sure if this is the latest version: [faktura-specifikation-2018-02.xlsx](https://github.com/on-api/on-api/files/4488960/faktura-specifikation-2018-02.xlsx)

**Comment by joeseos** [comment]
Suggestion on how we could provide a service to replace the .xls file transfer (sorry for the bad JSON):

`{
  "coId": {Metropolis Stadsnät},
  "name": {Tjänstebolaget},
  "population": {
    "referenceId": {abc123
      "subscriptionId": {12345
        "serviceName": {Öppet nät L3 - 250/100
          "serviceDescription": {Öppet nät L3 - 250/100}
        },
        "connectionDate": {2017-10-15},
        "disconnectionDate": {},
        "listPrice": {100},
        "billingItem": {},
        "rowType": {Periodic Fee},
        "fromDate": {2017-11-01},
        "toDate": {2017-11-30},
        "creditAmount": {100},
        "invoicedAmount": {}
      },
      "accessId": {aid-5678},
      "streetName": {Storgatan},
      "streetNumber": {12},
      "streetLittera": {a},
      "postalCode": {999 88},
      "city": {Metropolis},
      "apartmentNumber": {1402},
      "apartmentAddress": {},
      "apartmentOutlet": {}
    }
  }
}`

**Comment by thoho** [comment]
The specification does not say the file format should be .XLS but .CSV. The initial motivation for this is that it both can be easily parsed if the received would like to process it mechanically but also could be opened manually with Excel Google sheets or similar.
Invoice specifications is by their nature in many cases a by product of the invoice creation. When the time comes to issue an invoice the issuer basically needs to create the invoice specification first and the the invoice is a summary of the specification (with some added administrative info). The goal with the invoice specification was to work towards all SO/CO having the same or at least similar formats to simplify processing and cross-checking for the SP.
I just don't see the point for having the invoice specification being dynamically generated, is there a need?
If so, don't the query need to at least ask for the specification records for a certain invoice? For  certain SP?

**Comment by joeseos** [comment]
I use the specification for revenue / cost assurance, I.e. cleaning up services that we no longer have paying customers on. In my opinion, it's a limitation that this only can be processed once a month when the specifications is sent to us as a SP, something that a m2m solution might solve. I would say that the mismanagement of this process also leads to the "blocked port" scenario where the SP have not removed the service or services on the port when the customer churns or moves to a different address, blocking the new SP from ordering services.

Maybe the correct approach is to use accesses/feasibility or subscriptions API for this purpose?

**Comment by thoho** [comment]
OK. The explicit intent when the invoice specification was created was to provide a detailed breakdown for each issued invoice.
Ofc it would be preferable to have more refined way to synchronize service state between SP and SO/CO. The subscriptions API should be a starting point.
On the other hand, if provisioning and de-provisioning of services are handled through API one might want to look into the the reason for the state divergence? Can state changes occur on one side outside of the API calls? Or is one side not executing requested state change? Bad exception handling on either side etc?

**Comment by joeseos** [comment]
I agree. spReference and spSubscriptionId in the subscriptions API should be sufficient to find any discrepancies in the customers and services.

**Comment by joeseos** [comment]
My input om the invoice specification. 
[TLF_Faktura-specifikation-2021-02-17 - förslag TN.xlsx](https://github.com/on-api/on-api/files/5994509/TLF_Faktura-specifikation-2021-02-17.-.forslag.TN.xlsx)

**Comment by junetaw** [comment]
Invoice specification has a separate working group that processes this. It has an own channel on slack for inputs from outside. 
The above discussion is largely obselete. I close this.
