### ISSUE TITLE
Access: PremisesType - More enumerations needed

### ISSUE THREAD

**Issue by junetaw** [on-api/on-api#92]
With the future implementation of priceGroup the following may be relevant to add.

premisesType: 
There is a a need to add two more enumerations for Holiday homes (Fritidsboenden). 
Example HOLIDAY_HOUSE and HOLIDAY_MDU_APARTMENT.

In certain CO there is a separation of prices and/or technical services depending if the access is a residential, company or holiday house/apartment. For example you could have a "base" internet service (say 2/2 Mbit/s) for IoT that is active all year but the owner/renter could upgrade to a faster one for 1-x days and then it returns to the base. This is only available to Holiday homes.
In other COs there are 3-day, 7-day or 14-day prepaid services that should only be allowed on certain accesses.

In order to "know" it might be necessary to introduce two or more new enums.

The priceGroup field only gives what price list a certain access belongs to but premisesType is still needed to differentiate the type of access; for example if it is a consumer access or a company access. But also residential houses vs holiday houses.

**Comment by edruid** [comment]
I'm not against expanding the `premisesType` enum, but isn't this part of what the `services` endpoint is supposed to do? That is, tell what services are available for a given access.

**Comment by junetaw** [comment]
I think three changes are needed really:

1 A change:
"RESIDENTIAL_HOUSE Single family house (single dwelling unit)" should be changed to:
"SDU Single dwelling unit. It could be a single residential (family) house or an unit directly connected without on-premise access switch, in effect everyhing opposite to MDU."

2 Two additions:
SDU_HOLIDAY
MDU_APARTMENT_HOLIDAY

**Comment by teemufrosen** [comment]
Working group meeting: Needs further discussion and decision from working group for address. Will not be implemented in 2.6.0.
