### ISSUE TITLE
Accesses: Removal of four fields

### ISSUE THREAD

**Issue by junetaw** [on-api/on-api#94]
The Address and Invoice specification group wants to know if any of these four fields are in use anywhere or if they can be removed from the specification:

- coNetworkAgreement
- coFiberConverter
- coCpeSwitch
- coCpeRouter

**Comment by junetaw** [comment]
The Address and Invoice specification group then proposes that these fields should be removed from 2.6 unless anyone objects.

**Comment by teemufrosen** [comment]
Added to 2.6 project.
