### ISSUE TITLE
Accesses: Add PTS UUID value

### ISSUE THREAD

**Issue by junetaw** [on-api/on-api#96]
PTS (The Swedish Post and Telecom Authority) seems to have created its own list of Addresses over Sweden. Each address (note address, not access) have an UUID.
Every Access on the Address therefore share the same UUID.
This is needed for reporting purposes.

Propsal is to add this to the Accesses entity.

**Comment by MartinChristenssonOU** [comment]
I think the UUIDs are from Lantmäteriet. Or?
See for example. https://www.lantmateriet.se/globalassets/geodata/geodatatjanster/pb_inskrivning_direkt_v3.0.0_3.6.pdf

**Comment by junetaw** [comment]
I do not know. We have only received a 400+ MB tab separated csv-file where the headers are:
"uuidadrpl"	"gatunummer"	"fastbet"	"postnr"	"postort"	"kommunkod"	"kommun"	"gardsnamn"	"gata"

Where is it from? I do not know. 
How are we supposed to get the list? I do not know. 
How often is is updated? I do not know.
Are there other formats (json etc)? I do not know.

**Comment by MartinChristenssonOU** [comment]
I think you get it from Lantmäteriets APIs or other sources using this data
https://www.lantmateriet.se/sv/geodata/vara-produkter/produktlista/fastighetsinformation-nedladdning/
It replaces "fastighetsnyckel (FNR)" and "Riksnyckel".  
But mostly it is a better ID than Fastighetsbeteckning.

**Comment by junetaw** [comment]
I think we need more data and clarity from PTS and others so I moved the planned version to vnext and not 2.6. 
The Address- and Specification group might have to work here :)

**Comment by dejantep** [comment]
yes, this is data from Lantmäteriet and refers to addresses. But it should be noted that it doesnt take appartments into account, only address to premise.

**Comment by jonjacs** [comment]
Does it really refer to an adress? Is it not referring to a property designation (fastighetsbeteckning)? Since that is what you search in "registerbeteckning api" for to get the id which then can be used to search for more information in for example "inskrivning api".

**Comment by MartinChristenssonOU** [comment]
Jonas, you are correct, the UUID we think PTS is reffering to is the UUID for a property, not address. Eg.
https://geotorget.lantmateriet.se/dokumentation/GEODOK/4/latest/informationsinnehall.html
Lantmäteriet is using UUID for most of their objects in their databases.

**Comment by MartinChristenssonOU** [comment]
So I actually called PTS (Elisabeth Häggquist) and they use different UUIDs for different thing:
Bredbandskartläggning - UUID_adrpl - Adressplats i.e. one specific address - this would be most useful for service providers responding to PTS requests for info.
Seeking subsidies - UUID__regbygg - byggnad i.e. one specific building - this could be useful for an SP if no other address data is available
Lastly Lantmäteriet also have UUIDs for properties (fastigheter), but these are not used by PTS.
